name: Spotify to Plex
slug: spotify_to_plex
version: "1.0.104"

description: Sync Spotify playlists with Plex

arch:
  - aarch64
  - amd64

startup: application
boot: auto
init: false

ingress: false
ingress_port: 9030

host_network: true

ports:
  9030/tcp: null

map:
  - config:rw

options:
  spotify_api_client_id: ""
  spotify_api_client_secret: ""
  spotify_api_redirect_uri: ""
  encryption_key: ""
  plex_app_id: ""
  tidal_api_client_id: ""
  tidal_api_client_secret: ""
  lidarr_api_key: ""
  slskd_api_key: ""

schema:
  spotify_api_client_id: str
  spotify_api_client_secret: str
  spotify_api_redirect_uri: str
  encryption_key: str
  plex_app_id: str
  tidal_api_client_id: str
  tidal_api_client_secret: str
  lidarr_api_key: str
  slskd_api_key: str

environment:
  STORAGE_DIR: /data
  PORT: "9030"

build: .